# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Build
      run: GOOS=linux GOARCH=arm GOARM=7 go build -o player -v ./...
      working-directory: ./player
      
    # Leave 'player' binary as an artifact
    - name: Archive artifact
      uses: actions/upload-artifact@v3
      with:
        name: player
        path: ./player/player

    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v0.0.1')
      run: |
        # You can add any release creation commands here
        # For example:
        # Create a release draft
        gh release create v0.0.1 ./player/player --title "Release v0.0.1" --notes "Release notes for v0.0.1"

    # - name: Test
    #   run: go test -v ./...
